version: "3.7"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: "admin123"
      POSTGRES_DATABASE: "pmc"
      POSTGRES_PASSWORD: "admin123"
    volumes:
      - ./init.sql:/data/application/init.sql
  bubble_app:
    build: .
    command: sh -c "./wait-for.sh postgres:5432 -- ./bubble ./conf/config.ini"
    depends_on:
      - postgres
    ports:
      - "8888:8888"